import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
// import { MDXProvider } from "@mdx-js/react";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "400", "500", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter} ${inter.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
